version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Europe/Oslo"
    groups:
      maven-plugin:
        patterns:
          - "org.apache.maven.plugins:*"
      test-dependencies:
        patterns:
          - "org.junit.jupiter:*"
          - "org.mockito:*"
    ignore:
      # Bundled with Minecraft. Keep version in sync.
      - dependency-name: "org.apache.logging.log4j:log4j-core"
      # The Paper API for core will remain at the lowest supported version.
      - dependency-name: "io.papermc.paper:paper-api"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "12:00"
      timezone: "Europe/Oslo"
    groups:
      github-actions:
        update-types:
          - "major"
        patterns:
          - "*"
